# Basic Python

## 1. Split this string

In [3]:
s = "Hi there Sam!"

In [8]:
 s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [9]:
planet = "Earth"
diameter = 12742

Answer

In [10]:
txt="The diameter of{planet} is {diameter} kilometer.".format(planet="Earth",diameter=12742)
print(txt)

The diameter ofEarth is 12742 kilometer.

## 3. In this nest dictionary grab the word "hello"

In [11]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

Answer:

In [12]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [13]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
zeroarr=np.zeros(10)
print(zeroarr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [15]:
onesarr=np.ones(10)
print(onesarr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

## 5. Create an array of all the even integers from 20 to 35

In [16]:
rr=np.arange(20,35,2)
rr

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
sr=np.arange(0,9).reshape(3,3)
sr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [21]:
import pandas as pd

In [22]:
df = pd.DataFrame(index=np.arange(1,4),columns=np.arange(1,3))
print(df,df.shape)

     1    2
1  NaN  NaN
2  NaN  NaN
3  NaN  NaN (3, 2)

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [23]:
pd.date_range(start='01/01/2023', end='02/10/2023')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [24]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists)
df

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24